[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['py', 'python']

[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = ['py', 'python']
hock_add = '''
autocmd BufWritePost *.py call Flake8()
'''

[[plugins]]
repo = 'tell-k/vim-autopep8'
on_ft = ['py', 'python']
hock_add = '''
autocmd FileType python noremap <buffer> <S-f> :call Autopep8()<CR>
'''

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = 'go'
build = 'make'
depends = ['deoplete.nvim']
hook_source = '''
let g:deoplete#sources#go#gocode_binary = $GOPATH . '/bin/gocode'
set rtp+=$GOPATH/src/github.com/golang/lint/misc/vim
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = '''
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_fields = 1
let g:go_highlight_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1

let g:go_fmt_command = 'goimports'
let g:neomake_go_errcheck_maker = {
    \ 'args': ['-abspath'],
    \ 'append_file': 0,
    \ 'errorformat': '%f:%l:%c:\ %m, %f:%l:%c\ %#%m',
    \ }
    let g:neomake_go_enabled_makers = ['golint', 'govet']
    let g:go_gocode_unimported_packages = 1
    set noexpandtab
    set tabstop=4
    set shiftwidth=4
'''

# ruby formatter
[[plugins]]
repo = 'Chiel92/vim-autoformat'
hook_add = '''
let g:formatterpath = ['/home/staro/.anyenv/envs/rbenv/shims/']
let g:autoformat_autoindent = 0
let g:autoformat_retab = 0
let g:autoformat_remove_trailing_spaces = 0
autocmd FileType ruby,cucumber let b:autoformat_autoindent=1
autocmd FileType ruby,cucumber let b:autoformat_retab=1
autocmd FileType ruby,cucumber let b:autoformat_trailing_space=1
noremap <F3> :Autoformat<CR>
"au BufWrite * :Autoformat
'''

# ruby completion
[[plugins]]
repo = 'uplus/deoplete-solargraph'
on_ft = 'ruby'
depends = ['deoplete.nvim']

# ruby local variable highlight
[[plugins]]
repo = 'todesking/ruby_hl_lvar.vim'
on_ft = 'ruby'

# deoplete ruby
[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = 'ruby'
depends = 'deoplete.nvim'

# rdoc
[[plugins]]
repo = 'hallison/vim-rdoc'
on_ft = 'ruby'

# Ruby on Rails
[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['rails', 'ruby', 'eruby']
hook_add = '''
nnoremap [rails] <Nop>
nmap     <Leader>r [rails]
nnoremap [rails]r :Denite<Space>rails:
nnoremap <silent> [rails]d :<C-u>Denite<Space>rails:dwim<Return>
nnoremap <silent> [rails]m :<C-u>Denite<Space>rails:model<Return>
nnoremap <silent> [rails]c :<C-u>Denite<Space>rails:controller<Return>
nnoremap <silent> [rails]v :<C-u>Denite<Space>rails:view<Return>
nnoremap <silent> [rails]h :<C-u>Denite<Space>rails:helper<Return>
nnoremap <silent> [rails]t :<C-u>Denite<Space>rails:test<Return>
nnoremap <silent> [rails]s :<C-u>Denite<Space>rails:spec<Return>
'''

[[plugins]]
repo = '5t111111/denite-rails'
on_ft = ['rails', 'ruby', 'eruby']
depends = 'deoplete.nvim'


[[plugins]]
repo = 'robbles/logstash.vim'
on_ft = ['yaml','yml']

# JavaScript
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript']

# html tag close
[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['xml', 'html', 'eruby', 'xhtml', 'phtml']
hook_add = '''
let g:closetag_filetypes = 'html,xhtml,phtml,eruby'
'''
