name: test brew install

on: [pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: uninstall brew
      run: echo y | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)" || true
    - uses: actions/checkout@v1
    - name: Run make install
      run: make install

  zinit:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - run: brew install zsh

    - name: install zinit
      run: sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zinit/master/doc/install.sh)"

    - name: copy dotfiles
      run: make deploy

    - name: run zsh
      run: zsh

